package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
)

var artifactRE = regexp.MustCompile(`(?m)^ARTIFACT_PATH:\s*(.+?)\s*$`)
var phaseRE = regexp.MustCompile(`(?m)^TAKT_PHASE:\s*([A-Za-z0-9._-]+)\s*$`)
var pullRequestRE = regexp.MustCompile(`"pull_request"\s*:\s*([1-9][0-9]*)`)
var renderedArtifactRE = regexp.MustCompile("`([^`]+)`")

type checkpoint struct {
	Status       string    `json:"status"`
	Code         string    `json:"code"`
	Summary      string    `json:"summary"`
	Evidence     []string  `json:"evidence"`
	ArtifactPath string    `json:"artifact_path"`
	Findings     *[]string `json:"findings,omitempty"`
	Done         *bool     `json:"done,omitempty"`
}

func main() {
	raw, err := io.ReadAll(bufio.NewReader(os.Stdin))
	if err != nil {
		fail(err)
	}
	prompt := string(raw)
	phase := match(phaseRE, prompt)
	if phase == "" {
		handleGeneric(prompt)
		return
	}
	artifactPath := os.ExpandEnv(strings.TrimSpace(match(artifactRE, prompt)))
	status, code, summary := "ready", codeFor(phase), phase+" complete"
	evidence := []string{"fixture:" + phase}
	if blocked := os.Getenv("FAKE_BLOCK_PHASE"); blocked != "" && blocked == phase {
		status, code, summary = "blocked", blockedCodeFor(phase), "fixture requested a blocked checkpoint"
	}

	if status == "ready" {
		switch phase {
		case "issue-intake":
			out, err := exec.Command("gh", "issue", "view", "1", "--json", "number,title,body,state,labels").CombinedOutput()
			if err != nil {
				status, code, summary = "failed", "ISSUE_NOT_FOUND", string(out)
			}
			evidence = []string{strings.TrimSpace(string(out))}
		case "review-intake":
			pullRequest := "1"
			if os.Getenv("FAKE_FLOW_EVAL_SMOKE") == "1" {
				pullRequest = match(pullRequestRE, prompt)
				if pullRequest == "" {
					fail(fmt.Errorf("flow evaluation review input has no positive pull_request"))
				}
			}
			out, err := exec.Command("gh", "pr", "view", pullRequest, "--json", "number,title,state,baseRefName,headRefName").CombinedOutput()
			if err != nil {
				status, code, summary = "failed", "PR_NOT_FOUND", string(out)
			}
			evidence = []string{strings.TrimSpace(string(out))}
		case "issue-implementation", "plan-implementation", "piv-implementation":
			path := "app.txt"
			if extra := strings.TrimSpace(os.Getenv("FAKE_EXTRA_CHANGE_PATH")); extra != "" {
				path = extra
			}
			if err := os.MkdirAll(filepath.Dir(filepath.Join(mustWorkspace(), path)), 0o755); err != nil {
				fail(err)
			}
			if err := os.WriteFile(filepath.Join(mustWorkspace(), path), []byte("implemented by "+phase+"\n"), 0o644); err != nil {
				fail(err)
			}
		case "change-validation":
			marker := validationFailureMarker()
			if _, err := os.Stat(marker); err == nil {
				status, code, summary = "failed", "VALIDATION_FAILED", "fixture requested one recoverable validation failure"
				evidence = []string{"fixture validation exit=1"}
			}
		case "workflow-recovery":
			marker := validationFailureMarker()
			_ = os.Remove(marker)
			if err := os.WriteFile(filepath.Join(mustWorkspace(), "recovered.txt"), []byte("recovered\n"), 0o644); err != nil {
				fail(err)
			}
		case "pr-finalize":
			if err := finalizeGit(); err != nil {
				status, code, summary = "failed", "PR_CREATE_FAILED", err.Error()
			} else {
				out, err := exec.Command("gh", "pr", "create", "--draft", "--title", "fixture PR", "--body", "fixture body").CombinedOutput()
				if err != nil {
					status, code, summary = "failed", "PR_CREATE_FAILED", string(out)
				} else {
					evidence = []string{strings.TrimSpace(string(out))}
				}
			}
		}
		if phase == "review-synthesis" && os.Getenv("FAKE_REVIEW_CHANGES_REQUIRED") == "1" {
			code, summary = "REVIEW_CHANGES_REQUIRED", "fixture requested review fixes"
		}
		if phase == "review-fix" && os.Getenv("FAKE_REVIEW_CHANGES_REQUIRED") == "1" {
			code, summary = "REVIEW_FIXES_APPLIED", "fixture applied review fixes"
		}
	}

	if artifactPath == "" {
		artifactPath = filepath.Join(os.Getenv("TAKT_WORKSPACE"), ".takt", "fake-artifact-"+phase+".json")
	}
	if err := os.MkdirAll(filepath.Dir(artifactPath), 0o755); err != nil {
		fail(err)
	}
	artifactContent := []byte("# " + phase + "\n\nGenerated by isolated Takt fixture.\n")
	if strings.HasSuffix(artifactPath, ".json") {
		artifactContent, _ = json.MarshalIndent(map[string]any{"phase": phase, "status": status, "code": code, "evidence": evidence}, "", "  ")
		artifactContent = append(artifactContent, '\n')
	}
	if os.Getenv("FAKE_OMIT_ARTIFACT_PHASE") != phase {
		if err := os.WriteFile(artifactPath, artifactContent, 0o644); err != nil {
			fail(err)
		}
	}
	cp := checkpoint{Status: status, Code: code, Summary: summary, Evidence: evidence, ArtifactPath: artifactPath}
	if phase == "review-perspective" {
		empty := []string{}
		cp.Findings = &empty
	}
	if phase == "ralph-story" {
		value := true
		cp.Done = &value
	}
	encoded, _ := json.Marshal(cp)
	fmt.Print(string(encoded))
}

func handleGeneric(prompt string) {
	lower := strings.ToLower(prompt)
	if os.Getenv("FAKE_FLOW_EVAL_SMOKE") == "1" {
		if handleFlowEvaluationSmoke(prompt) {
			return
		}
	}
	if strings.Contains(lower, "semantic task router for takt") {
		if strings.TrimSpace(os.Getenv("FAKE_TASK_ROUTER_FORCE_TEMPLATE")) != "" {
			fmt.Print(`{"apiVersion":"takt/v1alpha1","kind":"TaskRoute","route":"template","template":"simple-reliable","reason":"fixture baseline forces the stable template","confidence":0.9,"signals":[],"controls":{"inspect_first":false,"baseline":false,"independent_tests":false,"enhanced_review":false,"max_parallel":2}}`)
			return
		}
		switch {
		case strings.Contains(lower, "fixture dynamic audit") || strings.Contains(lower, "fixture dynamic replan"):
			fmt.Print(`{"apiVersion":"takt/v1alpha1","kind":"TaskRoute","route":"dynamic","reason":"fixture requires task-specific decomposition","confidence":0.95,"signals":[],"controls":{"inspect_first":false,"baseline":false,"independent_tests":false,"enhanced_review":false,"max_parallel":2}}`)
		case strings.Contains(lower, `"goal":"change the public api safely"`) || strings.Contains(lower, `"goal":"изменить публичный api"`):
			fmt.Print(`{"apiVersion":"takt/v1alpha1","kind":"TaskRoute","route":"template","template":"simple-reliable","reason":"protected fixture change","confidence":0.9,"signals":["public_api"],"controls":{"inspect_first":false,"baseline":false,"independent_tests":false,"enhanced_review":false,"max_parallel":1}}`)
		default:
			fmt.Print(`{"apiVersion":"takt/v1alpha1","kind":"TaskRoute","route":"template","template":"simple-reliable","reason":"ordinary repository task","confidence":0.9,"signals":[],"controls":{"inspect_first":false,"baseline":false,"independent_tests":false,"enhanced_review":false,"max_parallel":2}}`)
		}
		return
	}
	if strings.Contains(lower, "capture the unchanged repository baseline") {
		fmt.Print(`{"summary":"fixture baseline","base_ref":"fixture-base","passed_checks":["fixture"],"known_failures":[],"unavailable_checks":[],"evidence":["fixture"]}`)
		return
	}
	if strings.Contains(lower, "design and add independent tests") {
		fmt.Print(`{"summary":"fixture independent tests","changed_files":[],"tests":["fixture: pass"],"assumptions":[]}`)
		return
	}
	if strings.Contains(lower, "bounded planner for dynamic takt") {
		goal := "fixture dynamic audit"
		if strings.Contains(lower, "fixture dynamic replan") {
			goal = "fixture dynamic replan"
		}
		fmt.Printf(`{"apiVersion":"takt/v1alpha1","kind":"WorkflowPlan","decision":"planned","goal":%q,"reason":"fixture needs discovery and synthesis","budget":{"max_child_runs":8,"max_parallel":2,"max_iterations":3,"max_tokens":100000},"phases":[{"id":"inventory","uses":"discover","objective":"discover fixture items","strategy":"task","checkpoint":true},{"id":"summary","uses":"synthesize","objective":"summarize fixture results","depends_on":["inventory"],"strategy":"task"}]}`, goal)
		return
	}
	if strings.Contains(lower, "reassessing a dynamic takt plan") {
		if strings.Contains(lower, "fixture dynamic replan") {
			fmt.Print(`{"action":"replace_remaining","reason":"fixture checkpoint replaces the remaining synthesis phase","phases":[{"id":"summary-replanned","uses":"synthesize","objective":"summarize revised fixture results","depends_on":["inventory"],"strategy":"task"}]}`)
			return
		}
		fmt.Print(`{"action":"continue","reason":"fixture evidence supports the remaining plan","phases":[]}`)
		return
	}
	if strings.Contains(lower, "bounded discovery phase") {
		fmt.Print(`{"summary":"fixture inventory","items":["item-a","item-b"]}`)
		return
	}
	if strings.Contains(lower, "investigate the requested scope") {
		fmt.Print(`{"summary":"fixture investigation","findings":["finding"],"evidence":["fixture"]}`)
		return
	}
	if strings.Contains(lower, "implement only the objective") {
		fmt.Print(`{"summary":"fixture implementation","changed_files":[],"tests":["fixture: pass"]}`)
		return
	}
	if strings.Contains(lower, "validate the requested result independently") {
		if marker := strings.TrimSpace(os.Getenv("FAKE_DYNAMIC_VALIDATE_FAIL_ONCE_FILE")); marker != "" {
			if _, err := os.Stat(marker); err == nil {
				if removeErr := os.Remove(marker); removeErr != nil {
					fail(removeErr)
				}
				fmt.Print(`{"summary":"fixture validation failed once","passed":false,"checks":["fixture: fail"],"issues":["recoverable fixture failure"]}`)
				return
			}
		}
		fmt.Print(`{"summary":"fixture validation","passed":true,"checks":["fixture: pass"],"issues":[]}`)
		return
	}
	if strings.Contains(lower, "review or adversarially verify") {
		fmt.Print(`{"summary":"fixture review","approved":true,"findings":[],"evidence":["fixture"]}`)
		return
	}
	if strings.Contains(lower, "synthesize the dynamic plan results") {
		fmt.Print(`{"summary":"fixture complete","completed":["inventory"],"unresolved":[],"next_actions":[]}`)
		return
	}
	if strings.Contains(lower, "reviewers") && strings.Contains(lower, "classify") {
		fmt.Print(`{"reviewers":["code","tests"],"complexity":"small","reason":"fixture"}`)
		return
	}
	if strings.Contains(lower, "ready=true") || strings.Contains(lower, "authorizes planning") || strings.Contains(lower, "return only json") && strings.Contains(lower, "ready") {
		fmt.Print(`{"ready":true}`)
		return
	}
	fmt.Print(`{"status":"ready","code":"FIXTURE_READY","summary":"generic fixture","evidence":["fixture"],"artifact_path":"fixture"}`)
}

func handleFlowEvaluationSmoke(prompt string) bool {
	workspace := os.Getenv("TAKT_WORKSPACE")
	if workspace == "" {
		fail(fmt.Errorf("TAKT_WORKSPACE is required for flow evaluation smoke"))
	}
	writeArtifact := func(name, body string) {
		path, err := renderedArtifactPath(prompt, name)
		if err != nil {
			fail(err)
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fail(err)
		}
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			fail(err)
		}
	}
	switch {
	case strings.Contains(prompt, "Implement the requested change"):
		if err := os.WriteFile(filepath.Join(workspace, "smoke.txt"), []byte("flow evaluation smoke\n"), 0o644); err != nil {
			fail(err)
		}
		writeArtifact("implementation.md", "fixture implementation\n")
	case strings.Contains(prompt, "Validate the current implementation"):
		cmd := exec.Command("go", "test", "./...")
		cmd.Dir = workspace
		if out, err := cmd.CombinedOutput(); err != nil {
			fail(fmt.Errorf("go test ./...: %s", strings.TrimSpace(string(out))))
		}
		writeArtifact("validation.md", "fixture validation\n")
	case strings.Contains(prompt, "Create or update a pull request"):
		if err := os.MkdirAll(filepath.Join(workspace, ".takt", "evals", "scm"), 0o755); err != nil {
			fail(err)
		}
		status := exec.Command("git", "status", "--porcelain")
		status.Dir = workspace
		out, err := status.Output()
		if err != nil {
			fail(err)
		}
		if strings.TrimSpace(string(out)) != "" {
			for _, argv := range [][]string{{"git", "add", "--all"}, {"git", "commit", "-m", "fixture flow evaluation"}} {
				cmd := exec.Command(argv[0], argv[1:]...)
				cmd.Dir = workspace
				if output, err := cmd.CombinedOutput(); err != nil {
					fail(fmt.Errorf("%s: %s", strings.Join(argv, " "), strings.TrimSpace(string(output))))
				}
			}
		}
		push := exec.Command("git", "push", "origin", "HEAD")
		push.Dir = workspace
		if out, err := push.CombinedOutput(); err != nil {
			fail(fmt.Errorf("git push origin HEAD: %s", strings.TrimSpace(string(out))))
		}
		var url []byte
		if os.Getenv("FAKE_SKIP_PR_CREATE") == "1" {
			url = []byte("https://example.test/example/mini-du/pull/1\n")
		} else {
			url, err = exec.Command("gh", "pr", "create", "--draft", "--title", "fixture PR", "--body", "fixture body").CombinedOutput()
			if err != nil {
				fail(fmt.Errorf("gh pr create: %s", strings.TrimSpace(string(url))))
			}
		}
		writeArtifact("pr.md", "fixture pull request\n")
		writeArtifact("pr-url.txt", string(url))
	case strings.Contains(prompt, "Summarize the completed workflow"):
		writeArtifact("summary.md", "fixture summary\n")
	case strings.Contains(prompt, "Perform an architectural sweep"):
		writeArtifact("architecture.md", "fixture architecture\n")
	case strings.Contains(prompt, "Create a concrete implementation plan"):
		writeArtifact("plan.md", "fixture plan\n")
	default:
		return false
	}
	fmt.Print("fixture flow evaluation smoke")
	return true
}

func renderedArtifactPath(prompt, baseName string) (string, error) {
	matches := renderedArtifactRE.FindAllStringSubmatch(prompt, -1)
	var found string
	for _, match := range matches {
		path := match[1]
		if filepath.IsAbs(path) && filepath.Base(path) == baseName {
			if found != "" {
				return "", fmt.Errorf("multiple rendered artifact paths for %s", baseName)
			}
			found = path
		}
	}
	if found == "" {
		return "", fmt.Errorf("missing rendered artifact path for %s", baseName)
	}
	return found, nil
}

func codeFor(phase string) string {
	return map[string]string{
		"git-prepare": "GIT_READY", "issue-intake": "ISSUE_READY", "issue-root-cause": "ROOT_CAUSE_CONFIRMED",
		"issue-reproduction": "ISSUE_REPRODUCED", "issue-fix-plan": "FIX_PLAN_READY", "issue-implementation": "IMPLEMENTATION_READY",
		"idea-research": "IDEA_RESEARCH_READY", "idea-plan": "IDEA_PLAN_READY", "plan-intake": "PLAN_CONFIRMED",
		"plan-implementation": "PLAN_IMPLEMENTED", "change-validation": "VALIDATION_PASSED", "workflow-recovery": "RECOVERY_APPLIED",
		"pr-finalize": "PR_READY", "workflow-final-summary": "WORKFLOW_COMPLETE", "review-intake": "REVIEW_READY",
		"review-perspective": "PERSPECTIVE_REVIEW_COMPLETE", "review-synthesis": "REVIEW_APPROVED", "review-fix": "REVIEW_NO_FIXES_REQUIRED",
		"piv-exploration": "EXPLORATION_READY_FOR_PLAN", "piv-plan": "PIV_PLAN_READY", "piv-implementation": "PIV_IMPLEMENTED",
		"ralph-prepare": "RALPH_BACKLOG_READY", "ralph-story": "RALPH_ALL_DONE", "ralph-summary": "RALPH_COMPLETE",
	}[phase]
}

func blockedCodeFor(phase string) string {
	return map[string]string{
		"git-prepare":            "GIT_DIRTY",
		"issue-intake":           "ISSUE_INPUT_AMBIGUOUS",
		"issue-root-cause":       "ROOT_CAUSE_UNCONFIRMED",
		"issue-reproduction":     "ISSUE_NOT_REPRODUCED",
		"issue-fix-plan":         "PLAN_CONTRACT_UNRESOLVED",
		"issue-implementation":   "IMPLEMENTATION_BLOCKED",
		"idea-research":          "IDEA_SCOPE_AMBIGUOUS",
		"idea-plan":              "IDEA_PLAN_CONTRACT_UNRESOLVED",
		"plan-intake":            "PLAN_SCOPE_AMBIGUOUS",
		"plan-implementation":    "PLAN_IMPLEMENTATION_BLOCKED",
		"change-validation":      "VALIDATION_FAILED",
		"workflow-recovery":      "RECOVERY_REQUIRES_HUMAN",
		"pr-finalize":            "PR_CREATE_FAILED",
		"workflow-final-summary": "WORKFLOW_INCOMPLETE",
		"review-intake":          "REVIEW_SCOPE_EMPTY",
		"review-fix":             "REVIEW_FIX_REQUIRES_DECISION",
		"piv-exploration":        "EXPLORATION_NEEDS_DECISION",
		"piv-plan":               "PIV_PLAN_NEEDS_DECISION",
		"piv-implementation":     "PIV_IMPLEMENTATION_BLOCKED",
		"ralph-prepare":          "RALPH_SCOPE_AMBIGUOUS",
		"ralph-story":            "RALPH_STORY_BLOCKED",
	}[phase]
}

func finalizeGit() error {
	workspace := mustWorkspace()
	paths := []string{"app.txt"}
	if _, err := os.Stat(filepath.Join(workspace, "recovered.txt")); err == nil {
		paths = append(paths, "recovered.txt")
	}
	if extra := strings.TrimSpace(os.Getenv("FAKE_EXTRA_CHANGE_PATH")); extra != "" {
		paths = append(paths, extra)
	}
	add := append([]string{"git", "add"}, paths...)
	commands := [][]string{add, {"git", "commit", "-m", "fixture implementation"}, {"git", "push", "-u", "origin", "HEAD"}}
	for _, argv := range commands {
		cmd := exec.Command(argv[0], argv[1:]...)
		cmd.Dir = workspace
		out, err := cmd.CombinedOutput()
		if err != nil {
			if argv[1] == "commit" && strings.Contains(string(out), "nothing to commit") {
				continue
			}
			return fmt.Errorf("%s: %s", strings.Join(argv, " "), strings.TrimSpace(string(out)))
		}
	}
	return nil
}

func validationFailureMarker() string {
	if value := os.Getenv("FAKE_VALIDATION_FAIL_FILE"); value != "" {
		return value
	}
	return filepath.Join(mustWorkspace(), ".force-validation-failure")
}

func mustWorkspace() string {
	value := os.Getenv("TAKT_WORKSPACE")
	if value == "" {
		value = "."
	}
	return value
}
func match(re *regexp.Regexp, value string) string {
	m := re.FindStringSubmatch(value)
	if len(m) > 1 {
		return m[1]
	}
	return ""
}
func fail(err error) { fmt.Fprintln(os.Stderr, err); os.Exit(1) }
