package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
)

var artifactRE = regexp.MustCompile(`(?m)^ARTIFACT_PATH:\s*(.+?)\s*$`)
var phaseRE = regexp.MustCompile(`(?m)^TAKT_PHASE:\s*([A-Za-z0-9._-]+)\s*$`)

type checkpoint struct {
	Status       string    `json:"status"`
	Code         string    `json:"code"`
	Summary      string    `json:"summary"`
	Evidence     []string  `json:"evidence"`
	ArtifactPath string    `json:"artifact_path"`
	Findings     *[]string `json:"findings,omitempty"`
	Done         *bool     `json:"done,omitempty"`
}

func main() {
	raw, err := io.ReadAll(bufio.NewReader(os.Stdin))
	if err != nil {
		fail(err)
	}
	prompt := string(raw)
	phase := match(phaseRE, prompt)
	if phase == "" {
		handleGeneric(prompt)
		return
	}
	artifactPath := os.ExpandEnv(strings.TrimSpace(match(artifactRE, prompt)))
	status, code, summary := "ready", codeFor(phase), phase+" complete"
	evidence := []string{"fixture:" + phase}
	if blocked := os.Getenv("FAKE_BLOCK_PHASE"); blocked != "" && blocked == phase {
		status, code, summary = "blocked", blockedCodeFor(phase), "fixture requested a blocked checkpoint"
	}

	if status == "ready" {
		switch phase {
		case "issue-intake":
			out, err := exec.Command("gh", "issue", "view", "1", "--json", "number,title,body,state,labels").CombinedOutput()
			if err != nil {
				status, code, summary = "failed", "ISSUE_NOT_FOUND", string(out)
			}
			evidence = []string{strings.TrimSpace(string(out))}
		case "review-intake":
			out, err := exec.Command("gh", "pr", "view", "1", "--json", "number,title,state,baseRefName,headRefName").CombinedOutput()
			if err != nil {
				status, code, summary = "failed", "PR_NOT_FOUND", string(out)
			}
			evidence = []string{strings.TrimSpace(string(out))}
		case "issue-implementation", "plan-implementation", "piv-implementation":
			if err := os.WriteFile(filepath.Join(mustWorkspace(), "app.txt"), []byte("implemented by "+phase+"\n"), 0o644); err != nil {
				fail(err)
			}
		case "change-validation":
			marker := validationFailureMarker()
			if _, err := os.Stat(marker); err == nil {
				status, code, summary = "failed", "VALIDATION_FAILED", "fixture requested one recoverable validation failure"
				evidence = []string{"fixture validation exit=1"}
			}
		case "workflow-recovery":
			marker := validationFailureMarker()
			_ = os.Remove(marker)
			if err := os.WriteFile(filepath.Join(mustWorkspace(), "recovered.txt"), []byte("recovered\n"), 0o644); err != nil {
				fail(err)
			}
		case "pr-finalize":
			if err := finalizeGit(); err != nil {
				status, code, summary = "failed", "PR_CREATE_FAILED", err.Error()
			} else {
				out, err := exec.Command("gh", "pr", "create", "--draft", "--title", "fixture PR", "--body", "fixture body").CombinedOutput()
				if err != nil {
					status, code, summary = "failed", "PR_CREATE_FAILED", string(out)
				} else {
					evidence = []string{strings.TrimSpace(string(out))}
				}
			}
		}
	}

	if artifactPath == "" {
		artifactPath = filepath.Join(os.Getenv("TAKT_WORKSPACE"), ".takt", "fake-artifact-"+phase+".json")
	}
	if err := os.MkdirAll(filepath.Dir(artifactPath), 0o755); err != nil {
		fail(err)
	}
	artifactContent := []byte("# " + phase + "\n\nGenerated by isolated Takt fixture.\n")
	if strings.HasSuffix(artifactPath, ".json") {
		artifactContent, _ = json.MarshalIndent(map[string]any{"phase": phase, "status": status, "code": code, "evidence": evidence}, "", "  ")
		artifactContent = append(artifactContent, '\n')
	}
	if err := os.WriteFile(artifactPath, artifactContent, 0o644); err != nil {
		fail(err)
	}
	cp := checkpoint{Status: status, Code: code, Summary: summary, Evidence: evidence, ArtifactPath: artifactPath}
	if phase == "review-perspective" {
		empty := []string{}
		cp.Findings = &empty
	}
	if phase == "ralph-story" {
		value := true
		cp.Done = &value
	}
	encoded, _ := json.Marshal(cp)
	fmt.Print(string(encoded))
}

func handleGeneric(prompt string) {
	lower := strings.ToLower(prompt)
	if strings.Contains(lower, "reviewers") && strings.Contains(lower, "classify") {
		fmt.Print(`{"reviewers":["code","tests"],"complexity":"small","reason":"fixture"}`)
		return
	}
	if strings.Contains(lower, "ready=true") || strings.Contains(lower, "authorizes planning") || strings.Contains(lower, "return only json") && strings.Contains(lower, "ready") {
		fmt.Print(`{"ready":true}`)
		return
	}
	fmt.Print(`{"status":"ready","code":"FIXTURE_READY","summary":"generic fixture","evidence":["fixture"],"artifact_path":"fixture"}`)
}

func codeFor(phase string) string {
	return map[string]string{
		"git-prepare": "GIT_READY", "issue-intake": "ISSUE_READY", "issue-root-cause": "ROOT_CAUSE_CONFIRMED",
		"issue-reproduction": "ISSUE_REPRODUCED", "issue-fix-plan": "FIX_PLAN_READY", "issue-implementation": "IMPLEMENTATION_READY",
		"idea-research": "IDEA_RESEARCH_READY", "idea-plan": "IDEA_PLAN_READY", "plan-intake": "PLAN_CONFIRMED",
		"plan-implementation": "PLAN_IMPLEMENTED", "change-validation": "VALIDATION_PASSED", "workflow-recovery": "RECOVERY_APPLIED",
		"pr-finalize": "PR_READY", "workflow-final-summary": "WORKFLOW_COMPLETE", "review-intake": "REVIEW_READY",
		"review-perspective": "PERSPECTIVE_REVIEW_COMPLETE", "review-synthesis": "REVIEW_APPROVED", "review-fix": "REVIEW_NO_FIXES_REQUIRED",
		"piv-exploration": "EXPLORATION_READY_FOR_PLAN", "piv-plan": "PIV_PLAN_READY", "piv-implementation": "PIV_IMPLEMENTED",
		"ralph-prepare": "RALPH_BACKLOG_READY", "ralph-story": "RALPH_ALL_DONE", "ralph-summary": "RALPH_COMPLETE",
	}[phase]
}

func blockedCodeFor(phase string) string {
	return map[string]string{
		"git-prepare":          "GIT_DIRTY",
		"issue-intake":         "ISSUE_INPUT_AMBIGUOUS",
		"issue-root-cause":     "ROOT_CAUSE_UNCONFIRMED",
		"issue-reproduction":   "ISSUE_NOT_REPRODUCED",
		"issue-fix-plan":       "PLAN_CONTRACT_UNRESOLVED",
		"issue-implementation": "IMPLEMENTATION_BLOCKED",
		"idea-research":        "IDEA_SCOPE_AMBIGUOUS",
		"idea-plan":            "IDEA_PLAN_CONTRACT_UNRESOLVED",
		"plan-intake":          "PLAN_SCOPE_AMBIGUOUS",
		"plan-implementation":  "PLAN_IMPLEMENTATION_BLOCKED",
		"change-validation":    "VALIDATION_FAILED",
		"workflow-recovery":    "RECOVERY_REQUIRES_HUMAN",
		"review-intake":        "REVIEW_SCOPE_EMPTY",
		"piv-exploration":      "EXPLORATION_NEEDS_DECISION",
		"piv-plan":             "PIV_PLAN_NEEDS_DECISION",
		"piv-implementation":   "PIV_IMPLEMENTATION_BLOCKED",
		"ralph-prepare":        "RALPH_SCOPE_AMBIGUOUS",
		"ralph-story":          "RALPH_STORY_BLOCKED",
	}[phase]
}

func finalizeGit() error {
	workspace := mustWorkspace()
	commands := [][]string{{"git", "add", "app.txt", "recovered.txt"}, {"git", "commit", "-m", "fixture implementation"}, {"git", "push", "-u", "origin", "HEAD"}}
	for _, argv := range commands {
		cmd := exec.Command(argv[0], argv[1:]...)
		cmd.Dir = workspace
		out, err := cmd.CombinedOutput()
		if err != nil {
			if argv[1] == "add" && strings.Contains(string(out), "pathspec") { // recovered.txt is optional
				cmd = exec.Command("git", "add", "app.txt")
				cmd.Dir = workspace
				out, err = cmd.CombinedOutput()
			}
			if err != nil && argv[1] == "commit" && strings.Contains(string(out), "nothing to commit") {
				continue
			}
			if err != nil {
				return fmt.Errorf("%s: %s", strings.Join(argv, " "), strings.TrimSpace(string(out)))
			}
		}
	}
	return nil
}

func validationFailureMarker() string {
	if value := os.Getenv("FAKE_VALIDATION_FAIL_FILE"); value != "" {
		return value
	}
	return filepath.Join(mustWorkspace(), ".force-validation-failure")
}

func mustWorkspace() string {
	value := os.Getenv("TAKT_WORKSPACE")
	if value == "" {
		value = "."
	}
	return value
}
func match(re *regexp.Regexp, value string) string {
	m := re.FindStringSubmatch(value)
	if len(m) > 1 {
		return m[1]
	}
	return ""
}
func fail(err error) { fmt.Fprintln(os.Stderr, err); os.Exit(1) }
